### ISSUE TITLE
ImportError: No module named tensorflow

### ISSUE THREAD

**Issue by Stigjb** [GoogleCloudPlatform/cloudml-samples#62]
### System information
- **OS Platform and Distribution**: Windows 10 Home 10.0.15063
- **TensorFlow version**: 1.2.0
- **Python version**: 3.5.3
- **Exact command to reproduce**: `gcloud ml-engine local train --module-name trainer.task --package-path trainer/ -- --train-files %TRAIN_DATA% --eval-files %EVAL_DATA% --train-steps 1000 --job-dir %MODEL_DIR% --eval-steps 100`

### Problem description
I am trying to get the *census* example in [Getting started](https://cloud.google.com/ml-engine/docs/how-tos/getting-started-training-prediction) to work on the command line in Windows. I am using Anaconda to set up the Python environment. Tensorflow is installed, it shows up in pip and I can import it without problem from the Python REPL. However, the module cannot be found running through `gcloud ml-engine local train`.
I have not modified the example code.

### Source code / logs
```
Traceback (most recent call last):
  File "C:\Users\<USER>\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\<USER>\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\bundledpython\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\<SOME_PATH>\cloudml-samples-master\census\estimator\trainer\task.py", line 4, in <module>
    import model
  File "trainer\model.py", line 20, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow
```

**Comment by Stigjb** [comment]
I have found the cause: gcloud uses different python binaries than the Anaconda environment I'm in, but I can control it with the `CLOUDSDK_PYTHON` environment variable. When it's set to a Python 2.7 executable, the error above occurs -- understandable since Tensorflow is unavailable on Python 2.7 on Windows.
Setting `CLOUDSDK_PYTHON` to a Python 3 executable with Tensorflow installed yields a different error:
```
ERROR: gcloud failed to load: invalid token (files.py, line 91)
    gcloud_main = _import_gcloud_main()
    import googlecloudsdk.gcloud_main
    from googlecloudsdk.calliope import base
    from googlecloudsdk.calliope import arg_parsers
    from googlecloudsdk.core import log
    from googlecloudsdk.core import properties
    from googlecloudsdk.core import config
    from googlecloudsdk.core.util import files as file_utils
    def MakeDir(path, mode=0777):
SyntaxError: invalid token

This usually indicates corruption in your gcloud installation or problems with your Python interpreter.

Please verify that the following is the path to a working Python 2.7 executable:
    C:\Users\<USER>\Anaconda3\envs\tensorflow\python.exe

If it is not, please set the CLOUDSDK_PYTHON environment variable to point to a working Python 2.7 executable.

If you are still experiencing problems, please reinstall the Cloud SDK using the instructions here:
    https://cloud.google.com/sdk/
```
I guess I'll just have to stick with the Google Cloud Shell for a while, then ...

**Comment by elibixby** [comment]
@Stigjb Yes `gcloud ml-engine local train` uses your default python binary to run TensorFlow. This means your default python binary should have TensorFlow installed. This *need not be the same binary used by gcloud* and you should *not* manually set the `CLOUDSDK_PYTHON` env var as you discovered. Instead use a tool like virtualenv to set your system's default python to a python 3 installation with TensorFlow installed, and leave gcloud's python alone. I haven't tried this on windows so it's possible there is something wrong. Please report back.

**Comment by arthurbarros** [comment]
@elibixby did the fix got pushed ? Running on the same issue here

**Comment by elibixby** [comment]
> Will probably be a couple weeks.

The gcloud sdk has a once a week release process. I will try to get it in this weeks release which means it will go out Wednesday. But it may not make it in, in which case it will go out the following wednesday

**Comment by elibixby** [comment]
Fix is submitted. It will come out with the gcloud release on 8/23. Thanks for your patience.

**Comment by shafy** [comment]
@elibixby I am still running into the same problem on MacOS with the SDK version 171.0.0 (it tries to use python 2 instead of 3 when running `gcloud ml-engine local train`). I am using python3's `venv` as my virtual environment. How do I fix this on MacOS?

**Comment by puneith** [comment]
This is a known issue and we have a fix for gcloud underway. I will respond here when the fix is available in gcloud.

**Comment by GuiHuaGaoGao** [comment]
> Fix is  submitted

@elibixby should `gcloud ml-engine local train` work with Python 3 on Windows now?
I'm still having the same issue: `ImportError: No module named tensorflow`

**Comment by puneith** [comment]
The gcloud issue has been fixed to work with Python3. In the mean time please also take a look at this PR which reconciles Python2 and Python3. Let me know if you have any questions.
